version: 2
jobs:
  build:
    working_directory: ~/unfollowNinja/unfollowNinja-server
    docker:
    - image: circleci/node:8.11.3
    - image: redis:4.0.10
    steps:
    - checkout:
        path: ~/unfollowNinja
    - restore_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
    - run:
        name: npm-install
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package-lock.json" }}
        paths:
        - ./node_modules
    - run:
        name: test
        command: npm test