version: '3'

services:
  workers:
    restart: always
    build: .
    depends_on:
      - postgres
      - redis-kue
      - redis
    volumes:
      - /data/workers-logs:/usr/src/app/logs
    environment:
      POSTGRES_URI: postgres://postgres@postgres
      REDIS_URI: redis://redis
      REDIS_KUE_URI: redis://redis-kue
  api:
    restart: always
    build: .
    command: ["node", "./dist/api.js"]
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - postgres
      - redis-kue
      - redis
    environment:
      POSTGRES_URI: postgres://postgres@postgres
      REDIS_URI: redis://redis
      REDIS_KUE_URI: redis://redis-kue
  postgres:
    restart: always
    image: postgres:13
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - /data/postgres:/var/lib/postgresql/data
  redis-kue:
    restart: always
    image: redis:5
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /data/redis-kue:/data
  redis:
    restart: always
    image: redis:5
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /data/redis:/data
