name: Server CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 13.x]
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        id: cache
        uses: actions/cache@preview
        with:
          path: unfollowNinja-server/node_modules
          key: node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
      - name: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./unfollowNinja-server
        run: npm ci
      - name: lint
        working-directory: ./unfollowNinja-server
        run: npm run lint
      - name: build
        working-directory: ./unfollowNinja-server
        run: npm run build
      - name: test
        working-directory: ./unfollowNinja-server
        run: npm run specs
